### ISSUE TITLE
101.o.o shows "Please wait for loading the projects ..."

### ISSUE THREAD

**Issue by cboltz** [openSUSE/mentoring#232]
This issue is about a problem in 101.o.o - and while it might also be a nice task for a future GSoC student, it's probably a good idea if one of the repo admins/devs fixes it before the next GSoC season starts ;-)

Instead of listing the available projects under Rancher/ibus/Uyuni etc., 101.o.o only displays "Please wait for loading the projects ..."

The browser's javascript console shows the following error:

```
Uncaught TypeError: tree is null
    convert_tree_to_html https://101.opensuse.org/assets/js/markdown.js:1556
    toHTMLTree           https://101.opensuse.org/assets/js/markdown.js:112
    toHTML               https://101.opensuse.org/assets/js/markdown.js:82
    success              https://101.opensuse.org/assets/js/github.js:42
    each                 jQuery
    success              https://101.opensuse.org/assets/js/github.js:15
    jQuery 8
        fire
        fireWith
        done
        callback
        send
        ajax
        method
        getJSON
    success              https://101.opensuse.org/assets/js/github.js:14
    jQuery 6
        fire
        fireWith
        done
        callback
        send
        ajax
    <anonymous>          https://101.opensuse.org/assets/js/github.js:8
    jQuery 9
        mightThrow
        process
        setTimeout handler*Deferred/then/resolve/<
        fire
        add
        then
        Deferred
        then
        ready
    <anonymous>          https://101.opensuse.org/assets/js/github.js:1
```

**Comment by ddemaio** [comment]
I tried to working on it and somehow accidentally pushed the changes to the main branch rather than the fork. I committed the previous code. I think this is a firefox issue. In other browsers, the items are viewable.

**Comment by ddemaio** [comment]
I tried 4 browsers. It works only with Brave. Not sure what the issue might be.

**Comment by cboltz** [comment]
I'm afraid this is still broken :-(

**Comment by ddemaio** [comment]
@cboltz Looks like it was working on my ff and brave. Is this on an old browser?

**Comment by cboltz** [comment]
New browsers - I tested with Firefox and Chromium on latest Tumbleweed, and in both the page is still broken.

The error message in the Firefox console is slightly different now:

```
Uncaught ReferenceError: markdown is not defined   <-- different error message
    <-- original report had 3 additional lines for markdown.js here -->
    success https://101.opensuse.org/assets/js/github.js:42
    each jQuery
    success https://101.opensuse.org/assets/js/github.js:15
    <-- everything else as in the original report -->
```

**Comment by anthony-e-stalker** [comment]
One thing that might help isolate the issue, is that the newest project (Daniel's) is displayed, but none of the older ones.

https://github.com/openSUSE/mentoring/issues/236

It's the only one that's displayed now. Previously, none of the projects were.

**Comment by ddemaio** [comment]
Yeah, I've been looking at a few things, but I just don't have the know how on this. It's really odd. Not understanding why the last one that was done worked, but the others didn't.

**Comment by ddemaio** [comment]
This is a bit odd as the new issues are added, the site only ends up showing that last issue updated. It removed #236 and is now showing #242

**Comment by SURYAS1306** [comment]
Hi @cboltz 

I’m currently exploring the GSoC 2026 ideas and contributing under several of them to better understand the ecosystem, as I’m very interested in contributing to openSUSE through GSoC 2026. During this process, I noticed this issue is still open and directly affects how the ideas are rendered on 101.o.o.

From the browser console stack trace:

```
Uncaught TypeError: tree is null
convert_tree_to_html → markdown.js
success → github.js
```

It appears that the Markdown conversion layer is receiving a null/invalid AST before rendering. Since earlier comments mention that only the most recently updated issue renders correctly, I’m wondering whether:

- The GitHub API response for older issues differs structurally

- Some project descriptions contain markdown that fails parsing

- `github.js` is not handling empty/null content defensively before passing it to `markdown.js`

I’m currently:

- Reviewing how `github.js` fetches and iterates over issues

- Comparing API responses for older vs newer issues

- Checking whether a defensive null-check before `convert_tree_to_html` would prevent the rendering failure

I’m very interested in contributing for GSoC 2026 and have been actively exploring both backend and frontend flows across the projects. I’ve previously contributed to Apache Dubbo and Apache CloudStack, where debugging cross-layer issues (API → transformation → rendering) required careful tracing of failure propagation. I’d be happy to investigate this further and try reproducing the issue locally to identify the root cause.

Please let me know if that would be helpful.
